from __future__ import annotations

from typing import Any

from ner.schema import NerDocument, NerEntity

DEMO_DOC_IDS = {
    "智能养鱼系统概览",
    "kimi-demo/智能养鱼系统概览",
}


def build_demo_ner_document(*, doc_id: str, source_text: str) -> NerDocument | None:
    if doc_id not in DEMO_DOC_IDS:
        return None

    entities = [
        _entity(
            doc_id=doc_id,
            entity_id="ent_demo_system",
            text="智能养鱼系统概览",
            normalized_text="智能养鱼系统概览",
            label="SYSTEM",
            start=0,
            end=8,
            source_sentence="智能养鱼系统概览页用于把设备连接、环境监测、用户需求和业务动作放进同一个上下文中理解。",
            occurrence_count=2,
            llm_description="Demo 系统总览页，承接设备连接、环境监测、用户需求与业务动作的统一视图。",
            llm_ran="系统入口与知识图谱总览",
            llm_ti="用于展示系统级概念与上下游主题关系。",
        ),
        _entity(
            doc_id=doc_id,
            entity_id="ent_demo_platform",
            text="Onenet",
            normalized_text="Onenet",
            label="PLATFORM",
            start=31,
            end=37,
            source_sentence="项目目标强调远距离网络测量并调节鱼缸温度、充氧、饲料添加和光照。",
            occurrence_count=2,
            llm_description="云端消息和控制回执的接入平台。",
            llm_ran="设备消息通路",
            llm_ti="承载设备事件与控制回执。",
        ),
        _entity(
            doc_id=doc_id,
            entity_id="ent_demo_monitoring",
            text="光照监测",
            normalized_text="光照监测",
            label="CAPABILITY",
            start=40,
            end=44,
            source_sentence="系统通过云平台接收设备事件与控制回执。",
            occurrence_count=2,
            llm_description="环境透明化的重要子能力，承接监测和告警视图。",
            llm_ran="环境监测子模块",
            llm_ti="展示光照相关监测能力。",
        ),
        _entity(
            doc_id=doc_id,
            entity_id="ent_demo_user",
            text="用户画像",
            normalized_text="用户画像",
            label="CAPABILITY",
            start=50,
            end=54,
            source_sentence="系统设计需要围绕不同用户场景做取舍。",
            occurrence_count=1,
            llm_description="用于区分不同使用角色和控制偏好。",
            llm_ran="用户分层服务",
            llm_ti="驱动系统权限与推荐策略。",
        ),
        _entity(
            doc_id=doc_id,
            entity_id="ent_demo_feed",
            text="自动投喂",
            normalized_text="自动投喂",
            label="CAPABILITY",
            start=60,
            end=64,
            source_sentence="自动投喂体现了远程控制在业务侧的落地。",
            occurrence_count=1,
            llm_description="远程控制在业务侧的关键落地能力。",
            llm_ran="控制执行能力",
            llm_ti="体现系统的自动化控制闭环。",
        ),
        _entity(
            doc_id=doc_id,
            entity_id="ent_demo_alert",
            text="告警中心",
            normalized_text="告警中心",
            label="CAPABILITY",
            start=68,
            end=72,
            source_sentence="项目目标强调远距离网络测量并调节鱼缸温度、充氧、饲料添加和光照。",
            occurrence_count=2,
            llm_description="聚合异常、阈值和通知策略的中心节点。",
            llm_ran="告警聚合与分发",
            llm_ti="用于汇总异常状态并联动用户。",
        ),
        _entity(
            doc_id=doc_id,
            entity_id="ent_demo_control",
            text="远程控制",
            normalized_text="远程控制",
            label="CAPABILITY",
            start=76,
            end=80,
            source_sentence="项目目标强调远距离网络测量并调节鱼缸温度、充氧、饲料添加和光照。",
            occurrence_count=1,
            llm_description="连接感知与执行的控制通路。",
            llm_ran="控制中枢",
            llm_ti="支撑控制动作的统一入口。",
        ),
        _entity(
            doc_id=doc_id,
            entity_id="ent_demo_console",
            text="远程控制台",
            normalized_text="远程控制台",
            label="INTERFACE",
            start=82,
            end=87,
            source_sentence="远程控制台是交互层节点，负责承接用户对系统的直接操作。",
            occurrence_count=2,
            llm_description="统一承接查看状态、下发命令和确认结果的交互入口。",
            llm_ran="控制操作台",
            llm_ti="用户执行远程操作的主入口。",
        ),
        _entity(
            doc_id=doc_id,
            entity_id="ent_demo_oxygen",
            text="增氧控制",
            normalized_text="增氧控制",
            label="CAPABILITY",
            start=89,
            end=93,
            source_sentence="增氧控制描述的是对鱼缸执行器的控制能力。",
            occurrence_count=1,
            llm_description="针对鱼缸执行器的环境调节控制能力。",
            llm_ran="执行器调节",
            llm_ti="体现环境控制的执行侧能力。",
        ),
        _entity(
            doc_id=doc_id,
            entity_id="ent_demo_device",
            text="设备台账",
            normalized_text="设备台账",
            label="DATA",
            start=95,
            end=99,
            source_sentence="依赖条件: 需要稳定的平台链路和明确的设备台账映射。",
            occurrence_count=1,
            llm_description="记录设备与映射关系的基础台账节点。",
            llm_ran="设备目录",
            llm_ti="帮助控制台找到真实设备。",
        ),
        _entity(
            doc_id=doc_id,
            entity_id="ent_demo_rules",
            text="控制安全规则",
            normalized_text="控制安全规则",
            label="RULE",
            start=101,
            end=107,
            source_sentence="远程授权流程落实控制安全规则中的授权和回执要求。",
            occurrence_count=1,
            llm_description="约束远程控制命令授权、回执和回滚的基础规则。",
            llm_ran="控制约束",
            llm_ti="用于规范控制动作边界。",
        ),
        _entity(
            doc_id=doc_id,
            entity_id="ent_demo_auth",
            text="远程授权流程",
            normalized_text="远程授权流程",
            label="PROCESS",
            start=109,
            end=116,
            source_sentence="远程授权流程用于保证控制命令在发出前经过身份确认、权限校验和操作留痕。",
            occurrence_count=1,
            llm_description="控制命令下发前的身份确认与权限校验流程。",
            llm_ran="命令审批链路",
            llm_ti="让远程控制可审计、可回滚。",
        ),
        _entity(
            doc_id=doc_id,
            entity_id="ent_demo_boiler",
            text="加热棒离水断电",
            normalized_text="加热棒离水断电",
            label="SAFETY",
            start=118,
            end=125,
            source_sentence="加热棒离水断电是系统里的安全冗余能力之一。",
            occurrence_count=1,
            llm_description="用于保护加热装置的安全冗余机制。",
            llm_ran="离水保护",
            llm_ti="避免硬件异常导致损坏。",
        ),
        _entity(
            doc_id=doc_id,
            entity_id="ent_demo_project",
            text="智能养鱼系统",
            normalized_text="智能养鱼系统",
            label="SYSTEM",
            start=127,
            end=133,
            source_sentence="智能养鱼系统概览页用于把设备连接、环境监测、用户需求和业务动作放进同一个上下文中理解。",
            occurrence_count=1,
            llm_description="系统总体能力集合，是概览页的上位概念。",
            llm_ran="系统总称",
            llm_ti="描述整个智能养鱼项目。",
        ),
    ]

    return NerDocument(doc_id=doc_id, source_text=source_text, entities=entities)


def _entity(
    *,
    doc_id: str,
    entity_id: str,
    text: str,
    normalized_text: str,
    label: str,
    start: int,
    end: int,
    source_sentence: str,
    occurrence_count: int,
    llm_description: str,
    llm_ran: str,
    llm_ti: str,
) -> NerEntity:
    return NerEntity(
        entity_id=entity_id,
        text=text,
        normalized_text=normalized_text,
        label=label,
        start=start,
        end=end,
        confidence=0.97,
        source_sentence=source_sentence,
        metadata={
            "mentions": [{"text": text, "start": start, "end": end, "confidence": 0.97}],
            "occurrence_count": occurrence_count,
            "source_sentences": [source_sentence],
            "normalization_notes": "demo-mock",
            "llm_enhanced": True,
            "llm_description": llm_description,
            "llm_ran": llm_ran,
            "llm_ti": llm_ti,
        },
    )
